version: '2'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_HTTP_AUTH_ENABLED
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3001:3001'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,andig-darksky-datasource
      - GF_USERS_AUTO_ASSIGN_ORG=false
      - GF_USERS_VIEWERS_CAN_EDIT=true
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com=587
      - GF_SMTP_USER=admin@emonindonesia.com
      - GF_SMTP_PASSWORD=8apG2&&k^mSa
      - GF_SMTP_SKIP_VERIFY=true
      - GF_SMTP_FROM_ADDRESS=admin@emonindonesia.com
      - GF_SMTP_FROM_NAME=NoReply
      - GF_AUTH.GENERIC_OAUTH_enabled=true
      - GF_AUTH.GENERIC_OAUTH_CLIENT_ID=monitor
      - GF_AUTH.GENERIC_OAUTH_CLIENT_SECRET="203de767-57ee-434d-9e12-3c0477dfb041
      - GF_AUTH.GENERIC_OAUTH_SCOPES=user:email
      - GF_AUTH.GENERIC_OAUTH_AUTH_URL=http//10.4.24.11:80/auth/realms/master/protocol/openid-connect/auth
      - GF_AUTH.GENERIC_OAUTH_TOKEN_URL=http//10.4.24.11:80/auth/realms/master/protocol/openid-connect/token
      - GF_AUTH.GENERIC_OAUTH_API_URL=http//10.4.24.11:80/auth/realms/master/protocol/openid-connect/userinfo
      - GF_AUTH.GENERIC_OAUTH_ALLOW_SIGN_UP=true
volumes:
  influxdb-storage:
  grafana-storage:
