version: '2'
services:
  influxdb:
    image: influxdb:latest
    #command: bash -c "influxd 2>&1 | tee -a /var/log/influxdb/influxdb.log"
    ports:
      - '8086:8086'
    volumes:
      #- ./logs:/var/log/influxdb
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    labels:
      - traefik.enable=true
      - traefik.port=8086
      - traefik.docker.network=web
      - traefik.backend=influxdb

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3002:3002'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,andig-darksky-datasource
      - GF_SERVER_HTTP_PORT=3002
      - GF_DEFAULT_INSTANCE_NAME=emon_docker11
      - GF_SERVER_DOMAIN=monitor.emonindonesia.com
      - GF_SERVER_ROOT_URL=https://monitor.emonindonesia.com/
      - GF_USERS_AUTO_ASSIGN_ORG=false
      - GF_USERS_VIEWERS_CAN_EDIT=true
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com=587
      - GF_SMTP_USER=admin@emonindonesia.com
      - GF_SMTP_PASSWORD=8apG2&&k^mSa
      - GF_SMTP_SKIP_VERIFY=true
      - GF_SMTP_FROM_ADDRESS=admin@emonindonesia.com
      - GF_SMTP_FROM_NAME=NoReply
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_NAME=Auth0
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=qDqQ8WwgIv4Qmuh1Z2Gh0FXYYc3b9p3b
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=NKn1kU6Vi7rhv85ds27Zx5z2xMO-U6gEpOcevv2vwyI3OjAFPNqSSjv8tIx3uJeI
      - GF_AUTH_GENERIC_OAUTH_SCOPES=openid profile email
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://dev-26a0tvto.auth0.com/authorize
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://dev-26a0tvto.auth0.com/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=https://dev-26a0tvto.auth0.com/userinfo
      - GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=true
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:monitor.emonindonesia.com
      - traefik.port=3002
      - traefik.docker.network=web
      - traefik.backend=monitor

volumes:
  influxdb-storage:
  grafana-storage:
